Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from buildingmotif.ingresses.bacnet import BACnetNetwork

bacnet = BACnetNetwork("172.24.0.1/32") # don't change this if you are using the docker compose setup
for rec in bacnet.records:
    print(rec)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mbuildingmotif[39;00m[38;5;21;01m.[39;00m[38;5;21;01mingresses[39;00m[38;5;21;01m.[39;00m[38;5;21;01mbacnet[39;00m [38;5;28;01mimport[39;00m BACnetNetwork
[0;32m----> 3[0m bacnet [38;5;241m=[39m [43mBACnetNetwork[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m172.24.0.1/32[39;49m[38;5;124;43m"[39;49m[43m)[49m [38;5;66;03m# don't change this if you are using the docker compose setup[39;00m
[1;32m      4[0m [38;5;28;01mfor[39;00m rec [38;5;129;01min[39;00m bacnet[38;5;241m.[39mrecords:
[1;32m      5[0m     [38;5;28mprint[39m(rec)

File [0;32m/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/buildingmotif/ingresses/bacnet.py:35[0m, in [0;36mBACnetNetwork.__init__[0;34m(self, ip)[0m
[1;32m     26[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     27[0m [38;5;124;03mReads a BACnet network to discover the devices and objects therein[39;00m
[1;32m     28[0m 
[0;32m   (...)[0m
[1;32m     31[0m [38;5;124;03m:type ip: Optional[str], optional[39;00m
[1;32m     32[0m [38;5;124;03m"""[39;00m
[1;32m     33[0m [38;5;66;03m# create the network object; this will handle scans[39;00m
[1;32m     34[0m [38;5;66;03m# Be a good net citizen: do not ping BACnet devices[39;00m
[0;32m---> 35[0m [38;5;28mself[39m[38;5;241m.[39mnetwork [38;5;241m=[39m [43mBAC0[49m[38;5;241m.[39mconnect(ip[38;5;241m=[39mip, ping[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m     36[0m [38;5;66;03m# initiate discovery of BACnet networks[39;00m
[1;32m     37[0m [38;5;28mself[39m[38;5;241m.[39mnetwork[38;5;241m.[39mdiscover()

[0;31mNameError[0m: name 'BAC0' is not defined
NameError: name 'BAC0' is not defined

