Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/nbclient/client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load manifest into BuildingMOTIF as its own library!
manifest = Library.load(ontology_graph="tutorial2_manifest.ttl")
# set it as the manifest for the model
model.update_manifest(manifest)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 4[0m
[1;32m      2[0m manifest [38;5;241m=[39m Library[38;5;241m.[39mload(ontology_graph[38;5;241m=[39m[38;5;124m"[39m[38;5;124mtutorial2_manifest.ttl[39m[38;5;124m"[39m)
[1;32m      3[0m [38;5;66;03m# set it as the manifest for the model[39;00m
[0;32m----> 4[0m [43mmodel[49m[38;5;241;43m.[39;49m[43mupdate_manifest[49m[43m([49m[43mmanifest[49m[43m)[49m

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/model.py:315[0m, in [0;36mModel.update_manifest[0;34m(self, manifest)[0m
[1;32m    308[0m [38;5;28;01mdef[39;00m [38;5;21mupdate_manifest[39m([38;5;28mself[39m, manifest: ShapeCollection):
[1;32m    309[0m [38;5;250m    [39m[38;5;124;03m"""Updates the manifest for this model by adding in the contents[39;00m
[1;32m    310[0m [38;5;124;03m    of the shape graph inside the provided SHapeCollection[39;00m
[1;32m    311[0m 
[1;32m    312[0m [38;5;124;03m    :param manifest: the ShapeCollection containing additional shapes against which to validate this model[39;00m
[1;32m    313[0m [38;5;124;03m    :type manifest: ShapeCollection[39;00m
[1;32m    314[0m [38;5;124;03m    """[39;00m
[0;32m--> 315[0m     [38;5;28mself[39m[38;5;241m.[39mget_manifest()[38;5;241m.[39mgraph [38;5;241m+[39m[38;5;241m=[39m [43mmanifest[49m[38;5;241;43m.[39;49m[43mgraph[49m

[0;31mAttributeError[0m: 'Library' object has no attribute 'graph'
AttributeError: 'Library' object has no attribute 'graph'

