Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
validation_result = model.validate()
print(f"Model is valid? {validation_result.valid}")

# print reasons
for entity, errors in validation_result.diffset.items():
    print(entity)
    for err in errors:
        print(f" - {err.reason()}")
------------------

----- stderr -----
2025-06-16 23:34:34,260 | buildingmotif.dataclasses.shape_collection |  WARNING: Could not resolve import of urn:ashrae/g36 from Libraries (Name: urn:ashrae/g36). Trying shape collections
----- stderr -----
2025-06-16 23:34:34,266 | buildingmotif.dataclasses.shape_collection |  WARNING: Could not resolve import of urn:ashrae/g36 from Libraries. Trying shape collections
----- stderr -----
2025-06-16 23:34:34,366 | buildingmotif.dataclasses.shape_collection |  WARNING: Could not resolve import of https://brickschema.org/schema/1.4/Brick from Libraries (Name: https://brickschema.org/schema/1.4/Brick). Trying shape collections
----- stderr -----
2025-06-16 23:34:34,374 | buildingmotif.dataclasses.shape_collection |  WARNING: Could not resolve import of https://brickschema.org/schema/1.4/Brick from Libraries. Trying shape collections
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m validation_result [38;5;241m=[39m [43mmodel[49m[38;5;241;43m.[39;49m[43mvalidate[49m[43m([49m[43m)[49m
[1;32m      2[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mModel is valid? [39m[38;5;132;01m{[39;00mvalidation_result[38;5;241m.[39mvalid[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m      4[0m [38;5;66;03m# print reasons[39;00m

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/model.py:218[0m, in [0;36mModel.validate[0;34m(self, shape_collections, error_on_missing_imports, shacl_engine)[0m
[1;32m    194[0m [38;5;250m[39m[38;5;124;03m"""Validates this model against the given list of ShapeCollections.[39;00m
[1;32m    195[0m [38;5;124;03mIf no list is provided, the model will be validated against the model's "manifest".[39;00m
[1;32m    196[0m [38;5;124;03mIf a list of shape collections is provided, the manifest will *not* be automatically[39;00m
[0;32m   (...)[0m
[1;32m    215[0m [38;5;124;03m:rtype: ValidationContext[39;00m
[1;32m    216[0m [38;5;124;03m"""[39;00m
[1;32m    217[0m compiled_model [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcompile(shape_collections [38;5;129;01mor[39;00m [[38;5;28mself[39m[38;5;241m.[39mget_manifest()])
[0;32m--> 218[0m [38;5;28;01mreturn[39;00m [43mcompiled_model[49m[38;5;241;43m.[39;49m[43mvalidate[49m[43m([49m[43merror_on_missing_imports[49m[43m)[49m

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/compiled_model.py:145[0m, in [0;36mCompiledModel.validate[0;34m(self, error_on_missing_imports)[0m
[1;32m    143[0m [38;5;66;03m# aggregate shape graphs[39;00m
[1;32m    144[0m [38;5;28;01mfor[39;00m sc [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mshape_collections:
[0;32m--> 145[0m     shapeg [38;5;241m+[39m[38;5;241m=[39m [43msc[49m[38;5;241;43m.[39;49m[43mresolve_imports[49m[43m([49m
[1;32m    146[0m [43m        [49m[43merror_on_missing_imports[49m[38;5;241;43m=[39;49m[43merror_on_missing_imports[49m
[1;32m    147[0m [43m    [49m[43m)[49m[38;5;241m.[39mgraph
[1;32m    148[0m [38;5;66;03m# inline sh:node for interpretability[39;00m
[1;32m    149[0m shapeg [38;5;241m=[39m rewrite_shape_graph(shapeg)

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/shape_collection.py:137[0m, in [0;36mShapeCollection.resolve_imports[0;34m(self, recursive_limit, error_on_missing_imports)[0m
[1;32m    120[0m [38;5;250m[39m[38;5;124;03m"""Resolves `owl:imports` to as many levels as requested.[39;00m
[1;32m    121[0m 
[1;32m    122[0m [38;5;124;03mBy default, all `owl:imports` are recursively resolved. This limit can[39;00m
[0;32m   (...)[0m
[1;32m    134[0m [38;5;124;03m:rtype: ShapeCollection[39;00m
[1;32m    135[0m [38;5;124;03m"""[39;00m
[1;32m    136[0m resolved_namespaces: Set[rdflib[38;5;241m.[39mURIRef] [38;5;241m=[39m [38;5;28mset[39m()
[0;32m--> 137[0m resolved [38;5;241m=[39m [43m_resolve_imports[49m[43m([49m
[1;32m    138[0m [43m    [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgraph[49m[43m,[49m
[1;32m    139[0m [43m    [49m[43mrecursive_limit[49m[43m,[49m
[1;32m    140[0m [43m    [49m[43mresolved_namespaces[49m[43m,[49m
[1;32m    141[0m [43m    [49m[43merror_on_missing_imports[49m[38;5;241;43m=[39;49m[43merror_on_missing_imports[49m[43m,[49m
[1;32m    142[0m [43m[49m[43m)[49m
[1;32m    143[0m new_sc [38;5;241m=[39m ShapeCollection[38;5;241m.[39mcreate()
[1;32m    144[0m new_sc[38;5;241m.[39madd_graph(resolved)

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/shape_collection.py:577[0m, in [0;36m_resolve_imports[0;34m(graph, recursive_limit, seen, error_on_missing_imports)[0m
[1;32m    574[0m             [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124mCould not resolve import of [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, ontology)
[1;32m    575[0m         [38;5;28;01mcontinue[39;00m
[0;32m--> 577[0m     dependency [38;5;241m=[39m [43m_resolve_imports[49m[43m([49m
[1;32m    578[0m [43m        [49m[43msc_to_add[49m[38;5;241;43m.[39;49m[43mgraph[49m[43m,[49m
[1;32m    579[0m [43m        [49m[43mrecursive_limit[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[38;5;241;43m1[39;49m[43m,[49m
[1;32m    580[0m [43m        [49m[43mseen[49m[43m,[49m
[1;32m    581[0m [43m        [49m[43merror_on_missing_imports[49m[38;5;241;43m=[39;49m[43merror_on_missing_imports[49m[43m,[49m
[1;32m    582[0m [43m    [49m[43m)[49m
[1;32m    583[0m     new_g [38;5;241m+[39m[38;5;241m=[39m dependency
[1;32m    584[0m [38;5;28;01mreturn[39;00m new_g

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/shape_collection.py:574[0m, in [0;36m_resolve_imports[0;34m(graph, recursive_limit, seen, error_on_missing_imports)[0m
[1;32m    572[0m [38;5;28;01mif[39;00m sc_to_add [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    573[0m     [38;5;28;01mif[39;00m error_on_missing_imports:
[0;32m--> 574[0m         [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124mCould not resolve import of [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, ontology)
[1;32m    575[0m     [38;5;28;01mcontinue[39;00m
[1;32m    577[0m dependency [38;5;241m=[39m _resolve_imports(
[1;32m    578[0m     sc_to_add[38;5;241m.[39mgraph,
[1;32m    579[0m     recursive_limit [38;5;241m-[39m [38;5;241m1[39m,
[1;32m    580[0m     seen,
[1;32m    581[0m     error_on_missing_imports[38;5;241m=[39merror_on_missing_imports,
[1;32m    582[0m )

[0;31mException[0m: ('Could not resolve import of %s', rdflib.term.URIRef('https://brickschema.org/schema/1.4/Brick'))

